### ISSUE TITLE
Cressi Cartesio Support

### ISSUE THREAD

**Issue by Colocoyo** [libdivecomputer/libdivecomputer#1]
Hi! 

I would like to contribute whatever I can so that your amazing dive computer tool - as well as the programs that use it - might be able to import/export/manage data coming from my Cressi Cartesio dive computer. The Cartesio, as far as I know, is identical to the Goa, at least in the context of software and file transfers.

I read your "contribute" section on the website. I am pretty good with computers, but my focus has usually been on the end-user side of things, so a lot of this is fairly new to me. Portmon does not work on my system, I assume because it is 64-bit. I downloaded a 14 day free trial of Serial Port Monitor, and used it to record a transfer from my Cartesio to the Crussi UCI PC software using cressi's own "HAL 9000" IR interface specifically made for the goa/cartesio.

I had the choice to export the logged data as .html, .txt (ANSI) or .txt (UNICODE), and went with the latermost. If you need it in one of the other two, please let me know. The files are below. 

Please tell me what else you need from a willing contributor in order to add this functionality to your tool. Thank you for the work you do!

On a side note, may I assume you are a diver? If so, what PC/mobile logbook software do you like personally? I have been researching the differences, and thus far have found with the exception of your project here, the entire industry is stuck in the 1990's, tech-wise. 

Many Thanks,
Cody

[libdc cartesio line file.txt](https://github.com/libdivecomputer/libdivecomputer/files/1985931/libdc.cartesio.line.file.txt)
[libdc cartesio modbus view.txt](https://github.com/libdivecomputer/libdivecomputer/files/1985932/libdc.cartesio.modbus.view.txt)
[libdc cartesio terminal view.txt](https://github.com/libdivecomputer/libdivecomputer/files/1985933/libdc.cartesio.terminal.view.txt)
[libdc cartesio dump file.txt](https://github.com/libdivecomputer/libdivecomputer/files/1985934/libdc.cartesio.dump.file.txt)

**Comment by calle-gunnarsson** [comment]
Have you tried to use [dctool](https://www.libdivecomputer.org/builds/stable/windows/dctool.exe) do get dumps?

For example
`dctool.exe -v -l cressi.log -f cressi download -o dive.%n.bin -f raw <COMx>`
or
`dctool.exe -v -l cressi.log -f cressi dump -o dive.bin <COMx>`

**Comment by jefdriesen** [comment]
Sorry for not responding earlier. It seems I forgot to enable notifications when I setup the github project, so I only noticed your ticket today. Oops.

Anyway, I took a quick look at your files, but it looks like they are incomplete. The opening of the serial port and the initial setup is missing, so you probably only captured a part of the communication. To capture the entire download sequence, you need to start capturing before you even start the Cressi application, and only stop after exiting the Cressi application.

**Comment by brendanhoran** [comment]
I've got a Goa.
I have just ordered a USB cable for it. 
I'd be happy to help get some dumps as directed in the "contribute" section.

I understand the Goa and the Cartesio are very similar.

**Comment by brendanhoran** [comment]
@jefdriesen 

I've used portmon to dump two connections. 
I hope its right. If not let me know what is missing/wrong and I can try again.

The files are : 
* cressi-goa-full-transfer.LOG , this is a full connection and download from the dive computer to the Cressi application
* cressi-goa-app-open.LOG, This is just a dump of attaching the USB interface while the Cressi application is running.

[cressi-goa-full-transfer.LOG](https://github.com/libdivecomputer/libdivecomputer/files/2544729/cressi-goa-full-transfer.LOG)
[cressi-goa-app-open.LOG](https://github.com/libdivecomputer/libdivecomputer/files/2544730/cressi-goa-app-open.LOG)

**Comment by jefdriesen** [comment]
Support for the Goa and Cartesio has been added in commit e363e5b1fd459fe8d79854ef63f3f561a29a7401.
