### ISSUE TITLE
Unable to have man

### ISSUE THREAD

**Issue by Patriboom** [libdivecomputer/libdivecomputer#10]
Hello again, 

sorry for so many questions submitted in « Issues ». 

I tried to compile the user manual doing
./Makefile

in the doc subdirectory.
Bellow the result:

```
./Makefile: ligne 19: erreur de syntaxe près du symbole inattendu « then »
./Makefile: ligne 19: `  if test -z '$(MAKELEVEL)'; then \'

```

Thanks for your help

**Comment by Patriboom** [comment]
If I do **make**

it results:  nothing to do

`make
Making all in man
make[1] : on entre dans le répertoire « ./libdivecomputer/doc/man »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « ./libdivecomputer/doc/man »
make[1] : on entre dans le répertoire « ./libdivecomputer/doc »
make[1]: rien à faire pour « all-am ».
make[1] : on quitte le répertoire « ./libdivecomputer/doc »
`

**Comment by jefdriesen** [comment]
Do you have `mandoc` and `doxygen` installed?

For this kind of question, you should use the [mailinglist](
https://www.libdivecomputer.org/cgi-bin/mailman/listinfo/devel). Tickets are for reporting bugs.
