### ISSUE TITLE
Download failed from Shearwater Perdix AI

### ISSUE THREAD

**Issue by chrisford** [libdivecomputer/libdivecomputer#11]
Hi,

Trying a Bluetooth download from my Perdix AI to 6.0.16.1 - get a DC_STATUS_TIMEOUT error.

(download worked fine to Shearwater Desktop)

Log:

`BLE Protocol:
00:00:533	Select device BluetoothLE#BluetoothLEc8:ff:28:0e:0f:c2-c8:77:47:18:b8:57
00:00:605	Device selected: Perdix
00:00:614	Number of Gatt Services: 3
00:00:615	Device ID: BluetoothLE#BluetoothLEc8:ff:28:0e:0f:c2-c8:77:47:18:b8:57
00:00:615	Is Paired: True
00:00:615	Protection Level: None
00:00:615	Starting to unpair...
00:00:714	Unpair Result: Unpaired
00:00:728	Is Paired: False
00:00:728	Starting to pair...
00:01:169	Connection status changed: Connected
00:01:393	Custom Pairing Kind: ConfirmOnly
00:01:393	Custom Pairing Pin: 
00:02:207	Pairing Result: Paired (1 Pairing Loops)
00:02:922	Connection status changed: Disconnected
00:03:011	Paired device name: Perdix
00:03:011	Number of Gatt Services: 3 (7 Pairing Loops)
00:03:012	Connected to service: fe25c237-0ece-443c-b0aa-e02033e7029d
00:03:039	Characteristics found: 27b7570b-359e-45a3-91bb-cf7e70049bd2 (Write/WriteWithoutResponse/Notify)
00:24:915	Failed to connect to device: BluetoothLE#BluetoothLEc8:ff:28:0e:0f:c2-c8:77:47:18:b8:57

INFO: libdivecomputer-0.dll version: 0.7.0-devel
INFO: Diving Log version: 6.0.16.1
INFO: Windows 10 (1809 | Build 17763), Version 6.3.17763`

**Comment by chrisford** [comment]
An update - it works if you start the download in Diving Log and THEN "Start Bluetooth" on the dive computer (apologies if this should have gone to Sven rather than here)

**Comment by jefdriesen** [comment]
It looks like setting up the BLE connection fails. That is before libdivecomputer comes into play. Anyway, glad to hear you already found a solution!
