### ISSUE TITLE
Cressi Goa freedive support

### ISSUE THREAD

**Issue by Cryosleeper** [libdivecomputer/libdivecomputer#12]
Hi,
I've run into an issue while importing a freedive data from Cressi Goa. Looks like it contains sample types not supported by libdive at the moment

WARNING: Unknown sample type 1. [in /win/subsurface/libdivecomputer/src/cressi_goa_parser.c:202 (cressi_goa_parser_samples_foreach)]
WARNING: Unknown sample type 2. [in /win/subsurface/libdivecomputer/src/cressi_goa_parser.c:202 (cressi_goa_parser_samples_foreach)]

Is it possible to add a support for this information?

I've run into this while using Subsurface but since it looks like a libdive issue I've filed reports with both parties.

Thanks in advance.

**Comment by jefdriesen** [comment]
Can you provide the reference data from the Cressi application? To be able to figure out the meaning of those unknown samples, I need to know how they are decoded by the Cressi application. Either the database from the application itself, or an export to some kind of human readable format (xml, csv, sqlite,...).

**Comment by Cryosleeper** [comment]
Hi @jefdriesen I'll give it a try today.

**Comment by Cryosleeper** [comment]
@jefdriesen here is the exported version of CressiUCI database.
[CressiUCI_all.txt](https://github.com/libdivecomputer/libdivecomputer/files/3881253/CressiUCI_all.txt)
From what I see right now those freedive data chunks are not really different from scuba ones so maybe UCI is converting it before storing. Is there any way to make a raw data dump from the computer?

**Comment by jefdriesen** [comment]
I have most of the freedive data format figured out. But I'm still missing one important piece of info: where and how the dive type (scuba/freedive) is stored in the data. I could use some more data to locate it. Anyone else with a Cressi Goa?

**Comment by Cryosleeper** [comment]
Any updates on this one?

**Comment by jefdriesen** [comment]
I still haven't figured out how to detect the difference between scuba dives and freedives. Do you have some extra dive data I could use?

**Comment by jefdriesen** [comment]
I think I have found the problem. The logbook index contains 5 bytes extra that are not present in the main dive data. One of those 5 bytes seems to contain the dive mode. That explains why I couldn't locate this info: it's simply not there. Really annoying issue, but at least I know where to look now.

**Comment by jefdriesen** [comment]
Fixed in master with commit 5b133233f75aa0cbf85ca1999c195aaf798b52db.
