### ISSUE TITLE
Mares Puck Pro+: Unexpected answer byte

### ISSUE THREAD

**Issue by info-kubu-at** [libdivecomputer/libdivecomputer#14]
Hi, I tried to import the divelog into subsurface v4.9.3 from my Mares Puck Pro+ (this is officially a different product than the Puck Pro) using the Mares bluelink pro (via Bluetooth). I tried this on a Window 10 device. I got following logfile from the application:
___
Subsurface: v4.9.3, built with libdivecomputer v0.7.0-devel-Subsurface-NG (ce6d9896a79afaa82641132e338f8744714c8593)
qt_ble_open( 00:1A:85:E0:0E:E0 )
connected to the controller for device 00:1A:85:E0:0E:E0
  .. discovering services
Found uuid: "{00001800-0000-1000-8000-00805f9b34fb}"
Found service "{00001800-0000-1000-8000-00805f9b34fb}"
 .. ignoring standard service "{00001800-0000-1000-8000-00805f9b34fb}"
Found uuid: "{544e326b-5b72-c6b0-1c46-41c1bc448118}"
Found service "{544e326b-5b72-c6b0-1c46-41c1bc448118}"
 .. created service object QLowEnergyService(0x1af074d0)
Found uuid: "{0000180a-0000-1000-8000-00805f9b34fb}"
Found service "{0000180a-0000-1000-8000-00805f9b34fb}"
 .. ignoring standard service "{0000180a-0000-1000-8000-00805f9b34fb}"
Found uuid: "{0000180f-0000-1000-8000-00805f9b34fb}"
Found service "{0000180f-0000-1000-8000-00805f9b34fb}"
 .. ignoring standard service "{0000180f-0000-1000-8000-00805f9b34fb}"
Found uuid: "{a86abc2d-d44c-442e-99f7-80059a873e36}"
Found service "{a86abc2d-d44c-442e-99f7-80059a873e36}"
 .. created service object QLowEnergyService(0x7aa3e90)
 .. done discovering services
Found service "{544e326b-5b72-c6b0-1c46-41c1bc448118}" "Unknown Service"
   c: "{1d1aae28-d2a8-91a1-1242-9d2973fbe571}"
        d: "{00002902-0000-1000-8000-00805f9b34fb}"
   c: "{99a91ebd-b21f-1689-bb43-681f1f55e966}"
   c: "{d8b3ab7c-4101-ec80-c441-9b0914f6ebc3}"
Found service "{a86abc2d-d44c-442e-99f7-80059a873e36}" "Unknown Service"
   c: "{1bd19c14-b78a-4e0f-aeb5-8e0352bac382}"
        d: "{00002902-0000-1000-8000-00805f9b34fb}"
   c: "{279f9dab-79be-4663-af1d-24407347af13}"
   c: "{6aa5711b-0376-44f1-bca1-8647b48bdb55}"
Using service "{544e326b-5b72-c6b0-1c46-41c1bc448118}" as preferred service
 .. enabling notifications
Using read characteristic "{1d1aae28-d2a8-91a1-1242-9d2973fbe571}"
now writing "0x0100" to the descriptor "{00002902-0000-1000-8000-00805f9b34fb}"
INFO: Open: transport=32
INFO: Configure: baudrate=115200, databits=8, parity=2, stopbits=0, flowcontrol=0
INFO: Timeout: value=1000
INFO: DTR: value=0
INFO: RTS: value=0
INFO: Purge: direction=3
QTime("00:04:04.206") packet SEND "c267"
INFO: Write: size=2, data=C267
QTime("00:04:04.206") packet WAIT
BLE write completed
INFO: Read: size=0, data=
ERROR: Failed to receive the answer. [in /win/subsurface/libdivecomputer/src/mares_iconhd.c:270 (mares_iconhd_packet)]
INFO: Purge: direction=1
QTime("00:04:05.212") packet SEND "c267"
INFO: Write: size=2, data=C267
QTime("00:04:05.212") packet WAIT
QTime("00:04:05.212") packet RECV "aa00000000000000000000000000000000000000"
QTime("00:04:05.212") packet RECV "0000000000000000000000000000000000000000"
QTime("00:04:05.212") packet RECV "0000000000000000000000000000000000000000"
QTime("00:04:05.212") packet READ "aa00000000000000000000000000000000000000"
INFO: Read: size=20, data=AA00000000000000000000000000000000000000
QTime("00:04:05.212") packet READ "0000000000000000000000000000000000000000"
INFO: Read: size=20, data=0000000000000000000000000000000000000000
QTime("00:04:05.212") packet READ "0000000000000000000000000000000000000000"
INFO: Read: size=20, data=0000000000000000000000000000000000000000
QTime("00:04:05.212") packet WAIT
QTime("00:04:05.711") packet RECV "00000000000000000000005075636b2050726f00"
QTime("00:04:05.711") packet READ "00000000000000000000005075636b2050726f00"
INFO: Read: size=20, data=00000000000000000000005075636B2050726F00
QTime("00:04:05.711") packet WAIT
QTime("00:04:06.208") packet RECV "0000000000000030342e30302e30300400000031"
QTime("00:04:06.208") packet RECV "34"
QTime("00:04:06.208") packet RECV "2d30342d31352b8b444330323400000000000000"
QTime("00:04:06.208") packet RECV "0000000000000000000000000000000000000000"
QTime("00:04:06.208") packet READ "0000000000000030342e30302e30300400000031"
INFO: Read: size=20, data=0000000000000030342E30302E30300400000031
QTime("00:04:06.208") packet READ "34"
INFO: Read: size=1, data=34
QTime("00:04:06.208") packet READ "2d30342d31352b8b444330323400000000000000"
INFO: Read: size=20, data=2D30342D31352B8B444330323400000000000000
QTime("00:04:06.208") packet READ "0000000000000000000000000000000000000000"
INFO: Read: size=20, data=0000000000000000000000000000000000000000
QTime("00:04:06.208") packet WAIT
QTime("00:04:06.709") packet RECV "ea"
QTime("00:04:06.709") packet RECV "aa00000000000000000000000000000000000000"
QTime("00:04:06.709") packet RECV "0000000000000000000000000000000000000000"
QTime("00:04:06.709") packet RECV "0000000000000000000000000000000000000000"
QTime("00:04:06.709") packet READ "ea"
INFO: Read: size=1, data=EA
Event: vendor=000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005075636B2050726F000000000000000030342E30302E30300400000031342D30342D31352B8B4443303234000000000000000000000000000000000000000000000000000000
.. write HIT with still incoming packets in queue
QTime("00:04:06.709") packet SEND "e742"
INFO: Write: size=2, data=E742
QTime("00:04:06.709") packet WAIT
INFO: Read: size=0, data=
ERROR: Failed to receive the answer. [in /win/subsurface/libdivecomputer/src/mares_iconhd.c:270 (mares_iconhd_packet)]
INFO: Purge: direction=1
QTime("00:04:07.717") packet SEND "e742"
INFO: Write: size=2, data=E742
QTime("00:04:07.717") packet WAIT
QTime("00:04:08.204") packet RECV "00000000000000000000005075636b2050726f00"
QTime("00:04:08.204") packet RECV "0000000000000030342e30302e30300400000031"
QTime("00:04:08.204") packet RECV "34"
QTime("00:04:08.204") packet RECV "2d30342d31352b8b444330323400000000000000"
QTime("00:04:08.204") packet READ "00000000000000000000005075636b2050726f00"
INFO: Read: size=20, data=00000000000000000000005075636B2050726F00
ERROR: Unexpected answer byte. [in /win/subsurface/libdivecomputer/src/mares_iconhd.c:276 (mares_iconhd_packet)]
INFO: Purge: direction=1
.. write HIT with still incoming packets in queue
QTime("00:04:08.204") packet SEND "e742"
INFO: Write: size=2, data=E742
QTime("00:04:08.204") packet WAIT
QTime("00:04:08.699") packet RECV "0000000000000000000000000000000000000000"
QTime("00:04:08.699") packet RECV "ea"
QTime("00:04:08.699") packet RECV "aa"
QTime("00:04:08.699") packet READ "0000000000000000000000000000000000000000"
INFO: Read: size=20, data=0000000000000000000000000000000000000000
ERROR: Unexpected answer byte. [in /win/subsurface/libdivecomputer/src/mares_iconhd.c:276 (mares_iconhd_packet)]
INFO: Purge: direction=1
.. write HIT with still incoming packets in queue
QTime("00:04:08.699") packet SEND "e742"
INFO: Write: size=2, data=E742
QTime("00:04:08.699") packet WAIT
INFO: Read: size=0, data=
ERROR: Failed to receive the answer. [in /win/subsurface/libdivecomputer/src/mares_iconhd.c:270 (mares_iconhd_packet)]
INFO: Purge: direction=1
QTime("00:04:09.703") packet SEND "e742"
INFO: Write: size=2, data=E742
QTime("00:04:09.703") packet WAIT
QTime("00:04:10.699") packet RECV "002d00000065007a002d00000061007a003b0000"
QTime("00:04:10.699") packet RECV "0064007a000300000065007a00400000005e0079"
QTime("00:04:10.699") packet RECV "006900080059007a003d00000055007b004d0000"
QTime("00:04:10.699") packet RECV "0055007e002f00000053007f0035000000510081"
QTime("00:04:10.699") packet READ "002d00000065007a002d00000061007a003b0000"
INFO: Read: size=20, data=002D00000065007A002D00000061007A003B0000
ERROR: Unexpected answer byte. [in /win/subsurface/libdivecomputer/src/mares_iconhd.c:276 (mares_iconhd_packet)]
ERROR: Failed to read the memory. [in /win/subsurface/libdivecomputer/src/mares_iconhd.c:943 (mares_iconhd_device_foreach)]
Deleting BLE object

**Comment by jefdriesen** [comment]
The timeout is too short for the BLE communication. Can you try with this build:

http://www.libdivecomputer.org/builds/experimental/windows/libdivecomputer-0.timeout.dll

Download the dll, remove the ".timeout" suffix from the filename, and drop the dll into the subsurface installation directory (backup the existing dll). Try to download your dives again, with the "Save libdivecomputer logfile" checkbox enabled.

**Comment by info-kubu-at** [comment]
Thank you very mutch, I tried it and it worked. But it was very slow. It took abount 1 min per dive (about 1h for 60 dives on the computer). I am very happy with the solution, because subsurface is realy nice. I would be very happy to have your patch on the subsurface-mobile application as well.
I can provide the libdivecomputer-log on request, but there are no errors (only INFO msgs).
In comparison to the Mares Mobile-Application or the myssi-app, they are faster much. It seems the waits with about 1000ms or 500ms are a bit long. Maybe, it is possible to optimize this a bit. Below, you find the timing from the subsurface_out.log:
----
Subsurface v4.9.3,
built with libdivecomputer v0.7.0-devel-Subsurface-NG (8711371728c4ee29dbe649084e13968fdec9ae0c)
built with Qt Version 5.12.0, runtime from Qt Version 5.12.0
built with libgit2 0.27.7
"validateGL(): created OpenGLContext."
"validateGL(): obtained QOpenGLFunctions."
"validateGL(): detected OpenGL version 4.6."
loading dive data from ("C:\\Users\\user\\AppData\\Roaming\\Subsurface\\user.xml")

File locations:

Unable to get local git directory
Cloud URL: No valid cloud credentials set.

Image filename table: C:\Users\user\AppData\Roaming\Subsurface/hashes
Local picture directory: C:\Users\user\AppData\Roaming\Subsurface/picturedata/

Starting download from  BT
downloading only new dives
qt_ble_open( 00:1A:85:E0:0E:E0 )
connected to the controller for device 00:1A:85:E0:0E:E0
  .. discovering services
Found uuid: "{00001800-0000-1000-8000-00805f9b34fb}"
Found service "{00001800-0000-1000-8000-00805f9b34fb}"
 .. ignoring standard service "{00001800-0000-1000-8000-00805f9b34fb}"
Found uuid: "{544e326b-5b72-c6b0-1c46-41c1bc448118}"
Found service "{544e326b-5b72-c6b0-1c46-41c1bc448118}"
 .. created service object QLowEnergyService(0x14a6fa70)
Found uuid: "{0000180a-0000-1000-8000-00805f9b34fb}"
Found service "{0000180a-0000-1000-8000-00805f9b34fb}"
 .. ignoring standard service "{0000180a-0000-1000-8000-00805f9b34fb}"
Found uuid: "{0000180f-0000-1000-8000-00805f9b34fb}"
Found service "{0000180f-0000-1000-8000-00805f9b34fb}"
 .. ignoring standard service "{0000180f-0000-1000-8000-00805f9b34fb}"
Found uuid: "{a86abc2d-d44c-442e-99f7-80059a873e36}"
Found service "{a86abc2d-d44c-442e-99f7-80059a873e36}"
 .. created service object QLowEnergyService(0x14a6f908)
 .. done discovering services
Found service "{544e326b-5b72-c6b0-1c46-41c1bc448118}" "Unknown Service"
   c: "{1d1aae28-d2a8-91a1-1242-9d2973fbe571}"
        d: "{00002902-0000-1000-8000-00805f9b34fb}"
   c: "{99a91ebd-b21f-1689-bb43-681f1f55e966}"
   c: "{d8b3ab7c-4101-ec80-c441-9b0914f6ebc3}"
Found service "{a86abc2d-d44c-442e-99f7-80059a873e36}" "Unknown Service"
   c: "{1bd19c14-b78a-4e0f-aeb5-8e0352bac382}"
        d: "{00002902-0000-1000-8000-00805f9b34fb}"
   c: "{279f9dab-79be-4663-af1d-24407347af13}"
   c: "{6aa5711b-0376-44f1-bca1-8647b48bdb55}"
Using service "{544e326b-5b72-c6b0-1c46-41c1bc448118}" as preferred service
 .. enabling notifications
Using read characteristic "{1d1aae28-d2a8-91a1-1242-9d2973fbe571}"
now writing "0x0100" to the descriptor "{00002902-0000-1000-8000-00805f9b34fb}"
BLE write completed
QTime("23:02:46.247") packet SEND "c267"
QTime("23:02:46.247") packet WAIT
QTime("23:02:47.749") packet RECV "aa00000000000000000000000000000000000000"
QTime("23:02:47.749") packet RECV "0000000000000000000000000000000000000000"
QTime("23:02:47.749") packet RECV "0000000000000000000000000000000000000000"
QTime("23:02:47.749") packet RECV "00000000000000000000005075636b2050726f00"
QTime("23:02:47.749") packet READ "aa00000000000000000000000000000000000000"
QTime("23:02:47.749") packet READ "0000000000000000000000000000000000000000"
QTime("23:02:47.749") packet READ "0000000000000000000000000000000000000000"
QTime("23:02:47.749") packet READ "00000000000000000000005075636b2050726f00"
QTime("23:02:47.749") packet WAIT
QTime("23:02:48.245") packet RECV "0000000000000030342e30302e303004000000"
QTime("23:02:48.245") packet RECV "31342d30342d31352b8b44433032340000000000"
QTime("23:02:48.245") packet RECV "0000000000000000000000000000000000000000"
QTime("23:02:48.245") packet RECV "0000ea"
QTime("23:02:48.245") packet READ "0000000000000030342e30302e303004000000"
QTime("23:02:48.245") packet READ "31342d30342d31352b8b44433032340000000000"
QTime("23:02:48.245") packet READ "0000000000000000000000000000000000000000"
QTime("23:02:48.245") packet READ "0000ea"
QTime("23:02:48.245") packet SEND "e742"
QTime("23:02:48.245") packet WAIT
QTime("23:02:49.244") packet RECV "aa"
QTime("23:02:49.244") packet READ "aa"
QTime("23:02:49.244") packet SEND "0c00000004000000"
QTime("23:02:49.244") packet WAIT
QTime("23:02:50.244") packet RECV "ff0a0000ea"
QTime("23:02:50.244") packet READ "ff0a0000ea"
QTime("23:02:50.245") packet SEND "e742"
QTime("23:02:50.245") packet WAIT
QTime("23:02:51.249") packet RECV "aa"
QTime("23:02:51.249") packet READ "aa"
QTime("23:02:51.249") packet SEND "0120000004000000"
QTime("23:02:51.249") packet WAIT
QTime("23:02:52.229") packet RECV "58c30200ea"
QTime("23:02:52.229") packet READ "58c30200ea"
QTime("23:02:52.229") packet SEND "e742"
QTime("23:02:52.229") packet WAIT
QTime("23:02:53.229") packet RECV "aa"
QTime("23:02:53.229") packet READ "aa"
QTime("23:02:53.229") packet SEND "58c2020000010000"
QTime("23:02:53.229") packet WAIT
QTime("23:02:54.239") packet RECV "0100000000005200010000000000520000000000"
QTime("23:02:54.239") packet RECV "0000530001000000000053000000000000005400"
QTime("23:02:54.239") packet RECV "0100000000005400010000000000540001000000"
QTime("23:02:54.239") packet RECV "0000550000000000000055000100000000005600"
QTime("23:02:54.239") packet READ "0100000000005200010000000000520000000000"
QTime("23:02:54.239") packet READ "0000530001000000000053000000000000005400"
QTime("23:02:54.239") packet READ "0100000000005400010000000000540001000000"
QTime("23:02:54.239") packet READ "0000550000000000000055000100000000005600"
QTime("23:02:54.239") packet WAIT
QTime("23:02:54.729") packet RECV "0100000000005700010000000000570001000000"
QTime("23:02:54.729") packet RECV "00005800010000000000590001000000"
QTime("23:02:54.729") packet RECV "000059000300000000005a000100000000005b00"
QTime("23:02:54.729") packet RECV "0100000000005c000000000000005c0004000000"
QTime("23:02:54.729") packet READ "0100000000005700010000000000570001000000"
QTime("23:02:54.729") packet READ "00005800010000000000590001000000"
QTime("23:02:54.729") packet READ "000059000300000000005a000100000000005b00"
QTime("23:02:54.729") packet READ "0100000000005c000000000000005c0004000000"
QTime("23:02:54.729") packet WAIT
QTime("23:02:55.229") packet RECV "00005c0001000000f2005502b3000f000b000700"
QTime("23:02:55.229") packet RECV "0b007700701500002b0078052080780532807805"
QTime("23:02:55.229") packet RECV "000000000800a81e00006900000000000000ef18"
QTime("23:02:55.229") packet RECV "ef18ef18ef18ef18ef18ef18ef18ef18ef184c00"
QTime("23:02:55.229") packet READ "00005c0001000000f2005502b3000f000b000700"
QTime("23:02:55.229") packet READ "0b007700701500002b0078052080780532807805"
QTime("23:02:55.229") packet READ "000000000800a81e00006900000000000000ef18"
QTime("23:02:55.229") packet READ "ef18ef18ef18ef18ef18ef18ef18ef18ef184c00"
QTime("23:02:55.229") packet WAIT
QTime("23:02:55.729") packet RECV "5c00e00025010000000000"
QTime("23:02:55.729") packet RECV "000000000000000a05ea"
QTime("23:02:55.729") packet READ "5c00e00025010000000000"
QTime("23:02:55.729") packet READ "000000000000000a05ea"
QTime("23:02:55.729") packet SEND "e742"
QTime("23:02:55.729") packet WAIT
QTime("23:02:57.217") packet RECV "aa"
QTime("23:02:57.217") packet READ "aa"
QTime("23:02:57.217") packet SEND "58c1020000010000"
QTime("23:02:57.217") packet WAIT
QTime("23:02:58.217") packet RECV "000010002c004e00570010002d004e0000001000"
QTime("23:02:58.217") packet RECV "30004e001900100031004e002d00100032004e00"
QTime("23:02:58.217") packet RECV "1e00000032004f002900000032004e0007000000"
QTime("23:02:58.217") packet RECV "31004e00330000002c004e00510000002c004e00"
QTime("23:02:58.217") packet READ "000010002c004e00570010002d004e0000001000"
QTime("23:02:58.217") packet READ "30004e001900100031004e002d00100032004e00"
QTime("23:02:58.217") packet READ "1e00000032004f002900000032004e0007000000"
QTime("23:02:58.217") packet READ "31004e00330000002c004e00510000002c004e00"
QTime("23:02:58.217") packet WAIT
QTime("23:02:58.717") packet RECV "0a0000002d004e003b0000002b004e007d000800"
QTime("23:02:58.717") packet RECV "21004e007a0008001500"
QTime("23:02:58.717") packet RECV "4e00c600080011004f00550000000f004e004400"
QTime("23:02:58.717") packet RECV "000005004f00a000080005004f00000000000400"
QTime("23:02:58.717") packet READ "0a0000002d004e003b0000002b004e007d000800"
QTime("23:02:58.717") packet READ "21004e007a0008001500"

**Comment by jefdriesen** [comment]
I already committed the fix with the longer timeout.

I'm not really sure why the download is much slower than the Mares application. Can you send the full log? For analyzing the timings, I need info from more packets.

**Comment by info-kubu-at** [comment]
Hi,
    
    Thx for the commit.
    
    You can download the full log on
    http://www.kubu.at/Yil1Soob/subsurface_timeout.log
    
    Can I support you with a "beer"?
    
    cu, Bernd
    
    Am 29.12.2019 um 13:18 schrieb Jef
      Driesen:
    
    
      
      I already committed the fix with the longer timeout.
      I'm not really sure why the download is much slower than the
        Mares application. Can you send the full log? For analyzing the
        timings, I need info from more packets.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/libdivecomputer/libdivecomputer/issues/14?email_source=notifications\u0026email_token=AOCBJS7WKGMJSBUBGLOCBQLQ3CIRNA5CNFSM4J7G42X2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHY6D6I#issuecomment-569500153",
"url": "https://github.com/libdivecomputer/libdivecomputer/issues/14?email_source=notifications\u0026email_token=AOCBJS7WKGMJSBUBGLOCBQLQ3CIRNA5CNFSM4J7G42X2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHY6D6I#issuecomment-569500153",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
