### ISSUE TITLE
enhancement: relax communication  channel restrictions

### ISSUE THREAD

**Issue by giffenk** [libdivecomputer/libdivecomputer#15]
Situation:
I have old Uwatec computers that support serial TTL interface (not true RS232, but who really cares....).

I was able to create a very simple Arduino based blob that reads the Uwatec serial data and then forwards it over Bluetooth.

SubSurface mobile rejected this solution as it claimed that libdivecomputer knew "Uwatecs did not support Bluetooth".  SubSurface desktop is happy with this world as Bluetooth seems to look like serial on the desktop.

So SubSurface desktop works for  me but mobile does not.

My suggestion is to remove  / relax communication channel restrictions. If it works let it happen?

P.S. I am happy to donate my Arduino blob code somewhere....

**Comment by jefdriesen** [comment]
There are two very different variants of Bluetooth communication: bluetooth classic (rfcomm) and bluetooth low energy (BLE). Bluetooth classic is indeed very similar to serial communication, and all desktop operation systems provide a serial port emulation mode. But BLE communcation is a completely different technology.

Based on your explanation, I assume your Arduino uses rfcomm? Subsurface mobile supports only BLE. That's probably the reason why it's not able to communicate with your Arduino. 

Libdivecomputer does have a built-in list of supported dive computers, and each dive computer in the list has an attribute with the supported transports (serial, usb, usbhid, rfcomm, ble). That enables applications to hide transports which are not supported by a particular dive computer. Giving users choices that are not going to work makes no sense. But the libdivecomputer api does not enforce this. It will use whatever transport the applications provided.

**Comment by glance-** [comment]
This is not a libdivecomputer issue, maybe if your stretching it a subsurface-mobile issue.

I'd suggest you just add bluetooth flags to the Uwatec properties and build yourself your own Subsurface-mobile, accepting your Arduino as a "Uwatec".
Just clone https://github.com/subsurface-divelog/subsurface , open libdivecomputer/src/descriptor.c and add `| DC_TRANSPORT_BLUETOOTH` to the descriptor line representing your model, and build a subsurface-mobile version that fits you.
