### ISSUE TITLE
Question: Is there a list of Shearwater BTLE request/response definitions?

### ISSUE THREAD

**Issue by ryanbooker** [libdivecomputer/libdivecomputer#18]
In the interests of learning, I'm doing some tinkering with BTLE on my Shearwater. Is there any documentation on the write commands and responses?

I'm sniffing around with PacketLogger on my Mac to find some, and can successfully grab some info (e.g. serial numbers, firmware version etc) in a little test app I wrote. But I couldn't find any documentation on what all the bytes actually mean. Some are relatively obvious, and while I can just copy what appears in the packet logger, I'd rather understand the packets in a more precise way. I couldn't find anything on the Shearwater website.

Anyway, if there is documentation somewhere I'd be grateful for a shove in the right direction. Cheers.

**Comment by jefdriesen** [comment]
Can you contact me by mail?
www.libdivecomputer.org/contact.html#personal
