### ISSUE TITLE
Missing bytes in a special case (Puck Pro, Linux platform)

### ISSUE THREAD

**Issue by h3llra1ser** [libdivecomputer/libdivecomputer#22]
Hello 

Using Subsurface Divelog, I stumbled upon a strange bug on communication with a Mares Puck Pro on linux platform.
The bug does not exist on windows os.
I've tested again with a fresh clone of the libdivecomputer repository and can confirm the following:

The buffer in dc_serial_read (posix) is missing the following byte if 0xEC is received.
In the following example, the 3 dropped bytes were a 0x00.

Look at the end of file dump-fail-linux.txt 
[dump-fail-linux.txt](https://github.com/libdivecomputer/libdivecomputer/files/7179256/dump-fail-linux.txt)
which gets a "timeout" because there are 3 bytes missing within the packet data.

NOTE: I've changed the packet size in my test to 512 bytes to match the packet size of the mares software dump (modified mares_iconhd.c):
	case PUCKPRO:
		device->layout = &mares_nemowide2_layout;
		device->packetsize = 512;
		break;

Below you see a comparison of "good" and "bad" buffer data.
First line: libdivecomputer puck pro dump
Second line: serial communication trace on windows platform

```
32 80 78 05 00 00 00 00 08 00 48 1F 00 00 3C 00
32 80 78 05 00 00 00 00 08 00 48 1f 00 00 3c 00   2€x.......H...<. 

00 00 00 00 49 00 95 18 4B 18 09 18 B0 18 94 19
00 00 00 00 49 00 95 18 4b 18 09 18 b0 18 94 19   ....I.•.K...°.”. 

2D 1A B2 1A CD 1A AC 1A 22 1A 77 00 E3 00 91 00
2d 1a b2 1a cd 1a ac 1a 22 1a 77 00 e3 00 91 00   -.².Í.¬.".w.ã.‘. 

17 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
17 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................ 

98 0F 00 00 19 00 ED 00 01 00 00 00 21 00 EC ??   ?? = Missing byte in buffer
98 0f 00 00 19 00 ed 00 01 00 00 00 21 00 ec 00   ˜.....í.....!.ì. 

15 00 00 00 21 00 EB 00 1B 00 00 00 1F 00 EB 00
15 00 00 00 21 00 eb 00 1b 00 00 00 1f 00 eb 00   ....!.ë.......ë. 

6C 00 08 00 1B 00 EC ?? 41 00 00 00 20 00 EB 00   ?? = Missing byte in buffer
6c 00 08 00 1b 00 ec 00 41 00 00 00 20 00 eb 00   l.....ì.A... .ë. 

00 00 00 00 22 00 EA 00 00 00 00 00 27 00 EA 00
00 00 00 00 22 00 ea 00 00 00 00 00 27 00 ea 00   ....".ê.....'.ê. 

00 00 00 00 33 00 E9 00 00 00 00 00 3D 00 E5 00
00 00 00 00 33 00 e9 00 00 00 00 00 3d 00 e5 00   ....3.é.....=.å. 

00 00 00 00 48 00 DB 00 00 00 00 00 50 00 D2 00
00 00 00 00 48 00 db 00 00 00 00 00 50 00 d2 00   ....H.Û.....P.Ò. 

00 00 00 00 59 00 CA 00 00 00 00 00 5F 00 C7 00
00 00 00 00 59 00 ca 00 00 00 00 00 5f 00 c7 00   ....Y.Ê....._.Ç. 

00 00 00 00 66 00 C0 00 00 00 00 00 6B 00 BD 00
00 00 00 00 66 00 c0 00 00 00 00 00 6b 00 bd 00   ....f.À.....k.½. 

00 00 00 00 73 00 B7 00 00 00 00 00 7D 00 B3 00
00 00 00 00 73 00 b7 00 00 00 00 00 7d 00 b3 00   ....s.·.....}.³. 

00 00 00 00 84 00 AA 00 00 00 00 00 8B 00 A6 00
00 00 00 00 84 00 aa 00 00 00 00 00 8b 00 a6 00   ....„.ª.....‹.¦. 

00 00 00 00 8D 00 9F 00 0F 00 00 00 95 00 9A 00
00 00 00 00 8d 00 9f 00 0f 00 00 00 95 00 9a 00   .....Ÿ.....•.š. 

00 00 00 00 9B 00 95 00 00 00 00 00 A2 00 8E 00
00 00 00 00 9b 00 95 00 00 00 00 00 a2 00 8e 00   ....›.•.....¢.Ž. 

00 00 00 00 A9 00 8B 00 00 00 00 00 AE 00 83 00
00 00 00 00 a9 00 8b 00 00 00 00 00 ae 00 83 00   ....©.‹.....®.ƒ. 

00 00 00 00 B4 00 83 00 04 00 00 00 C0 00 7D 00
00 00 00 00 b4 00 83 00 04 00 00 00 c0 00 7d 00   ....´.ƒ.....À.}. 

00 00 00 00 C2 00 7A 00 10 00 00 00 C9 00 79 00
00 00 00 00 c2 00 7a 00 10 00 00 00 c9 00 79 00   ....Â.z.....É.y. 

00 00 00 00 D4 00 77 00 00 00 00 00 E0 00 74 00
00 00 00 00 d4 00 77 00 00 00 00 00 e0 00 74 00   ....Ô.w.....à.t. 

00 00 00 00 E8 00 71 00 00 00 00 00 ED 00 6C 00
00 00 00 00 e8 00 71 00 00 00 00 00 ed 00 6c 00   ....è.q.....í.l. 

00 00 00 00 EC ?? 6A 00 2F 00 00 00 ED 00 69 00   ?? = Missing byte in buffer
00 00 00 00 ec 00 6a 00 2f 00 00 00 ed 00 69 00   ....ì.j./...í.i. 

rest of packet contains no 0xEC, so there are no bytes missing:

01 00 00 00 F0 00 68 00 00 00 00 00 F2 00 66 00
00 00 00 00 F4 00 65 00 07 00 00 00 F9 00 63 00
00 00 00 00 FE 00 62 00 00 00 00 00 FF 00 60 00
00 00 00 00 FF 00 5E 00 19 00 00 00 01 01 5E 00
00 00 00 00 07 01 5B 00 00 00 00 00 05 01 5A 00
32 00 00 00 04 01 5B 00 06 00 00 00 08 01 5A 00
06 00 00 00 03 01 59 00 95 00 0C 00 FE 00 59 00 
3D 00 00 00 FA 00 59 00 38 00 00 00 FA 00 59 00
06 00 00 00 FD 00 58 00 2D 00 00 00 FA 00 58 00
24 00 00 00 FC 00 57 00 00 00 00 00 00 01 56 00
EA

01 00 00 00 f0 00 68 00 00 00 00 00 f2 00 66 00   ....ð.h.....ò.f. 
00 00 00 00 f4 00 65 00 07 00 00 00 f9 00 63 00   ....ô.e.....ù.c. 
00 00 00 00 fe 00 62 00 00 00 00 00 ff 00 60 00   ....þ.b.....ÿ.`. 
00 00 00 00 ff 00 5e 00 19 00 00 00 01 01 5e 00   ....ÿ.^.......^. 
00 00 00 00 07 01 5b 00 00 00 00 00 05 01 5a 00   ......[.......Z. 
32 00 00 00 04 01 5b 00 06 00 00 00 08 01 5a 00   2.....[.......Z. 
06 00 00 00 03 01 59 00 95 00 0c 00 fe 00 59 00   ......Y.•...þ.Y. 
3d 00 00 00 fa 00 59 00 38 00 00 00 fa 00 59 00   =...ú.Y.8...ú.Y. 
06 00 00 00 fd 00 58 00 2d 00 00 00 fa 00 58 00   ....ý.X.-...ú.X. 
24 00 00 00 fc 00 57 00 00 00 00 00 00 01 56 00   $...ü.W.......V. 
ea                                                ê                
```

**Comment by jefdriesen** [comment]
This is indeed a strange issue. Our serial communication layer is just a thin wrapper around the operating system api. So if bytes are lost, that probably means they were already lost earlier. In the iconhd backend there is also no buffering going on, at least not for serial communication.

Can you provide some info on how you obtained the data you show? Libdivecomputer doesn't produce output like the one you show, so I assume you extracted the info somehow? If I understand you correctly, the first line is from downloading with subsurface on linux, right? But the second line is from the Mares application on Windows?. So I assume that means you sniffed the serial communication? If that's correct, can you also try downloading with dctool (or subsurface) on Windows. So we can compare results from the same software.

You say you increased the packet size to 512 bytes, but the dump-fail-linux.txt file does still show 256 packets. (The protocol supports arbitrary packet sizes, but using the "right" size is more efficient and faster.)

What kind of PC interface does the Puck Pro use? Is there a direct connection to the dive computer, or do you need to use some kind of dongle (like the Bluelink Pro or Dive Link 2 USB)? The reason why I'm asking is that with the Bluelink Pro there are know issues where sometimes bytes are dropped.

Are you using the exact same hardware for both the Windows and Linux system (e.g. a dual boot system), or is this with two different computers?

**Comment by h3llra1ser** [comment]
The attached text file is the verbose output of 
"dctool -v -d 'Mares Puck Pro' dump -o test.bin /dev/ttyUSB0"
dmesg: cp210x converter now attached to ttyUSB0
The Hardware is a DIY Puck adapter - simple TTL/USB. This adapter works on both linux and Windows (for all my past dives).
The failing dive transfer on linux is the first one which was a "deco" dive.
I've tested subsurface on windows too with the same adapter fetching the dive entry with the 0xEC 0x00 pair - works without any problem.

More info about the puck connection: Puck Pro <-> CP210x USB-to-Serial chip <-> PC USB Port

About packet size: 256bytes are fine, but I noted the 512 size change because the whole packet which I posted in the ticket was 512 bytes captured by the original mares software.
The attached text file (fail log) is an earlier run of dctool before I've matched the packet sizes.
The line-by-line comparison is the data of dctool, formatted with spaces and padded with "??" at the 3 places where dctool did not get the "00" byte.

**Comment by h3llra1ser** [comment]
I've re-read the Puck Pro just yet twice with the same settings: "force re-read of all dives" + "libdivecomputer logging" both enabled.
One time on Linux OS which gets the timeout on dive #4.
The other time on windows OS, which read all the stored dives successfully.
See the attached logs: 
[subsurface-libdivecomputer-win-linux.tar.gz](https://github.com/libdivecomputer/libdivecomputer/files/7187134/subsurface-libdivecomputer-win-linux.tar.gz)

And yes, I've used the same CP210x adapter on Linux and Windows.
Hope the logs will help.

**Comment by h3llra1ser** [comment]
https://github.com/torvalds/linux/blob/master/drivers/usb/serial/cp210x.c
line 444: here the 0xEC byte is defined as a "escape character" within the usb serial chip driver.
Maybe the problem lies another layer down?
I dont understand exactly what the two occurences do, but it seems that there is some unclean stuff in the driver?
Please take a look at lines 866
line 866: here the "escape" event gets triggered by 0xEC
line 873: the next byte in the dive log is a 0x00, which causes the driver to output the escape character itself and ignoring the 0x00

Am I missing something or could that be the problem?

**Comment by jefdriesen** [comment]
Yes, at first sight that appears to be the problem. The processing of the escape code is only active when [port_priv->event_mode](https://github.com/torvalds/linux/blob/master/drivers/usb/serial/cp210x.c#L934) is enabled, and that happens when [input parity checking](https://github.com/torvalds/linux/blob/master/drivers/usb/serial/cp210x.c#L1336) is enabled. And we do indeed configure even parity (DC_PARITY_EVEN) in the iconhd backend.

Can you check which serial line settings the Mares applications uses on Windows? I'll double check too, but I don't have any Mares dive computer to actually try, so I can only simulate one. But for this particular issue checking with real hardware would be better.

I'm surprised we haven't seen this before. The cp210x is used by Mares and some third-party Suunto interfaces:

https://www.libdivecomputer.org/drivers.html

Those are also the (only) two backends that use even/odd parity. Since we're transferring some binary data, the chance to encounter a 0xEC byte is very reasonable. Maybe because it's a fairly recent kernel change (Jul 14, 2020):

https://github.com/torvalds/linux/commit/a7207e9835a4f245c8c693170906fda0980273f3

**Comment by h3llra1ser** [comment]
Hm. I've tested on linux with disabled parity checks to circumvent the CP210x driver event code (see below).
Now I'm able to make a complete mem dump and also can extract all dive logs as xml.

Are you interested in the mem dump as a mares puck pro sample?
Ah and by the way I found the source again from which I built the puck pro dongle:
https://www.scubaboard.com/community/threads/mares-puck-pc-cable.381796/page-12#post-8071445

The changes in mares_iconhd.c below do not affect the driver bug, it only matches the packet size to the packet size which the original mares windows software is requesting from the hardware.
```
diff --git a/src/mares_iconhd.c b/src/mares_iconhd.c
index 21f88fa..de03183 100644
--- a/src/mares_iconhd.c
+++ b/src/mares_iconhd.c
@@ -547,6 +547,9 @@ mares_iconhd_device_open (dc_device_t **out, dc_context_t *context, dc_iostream_
                device->packetsize = 256;
                break;
        case PUCKPRO:
+               device->layout = &mares_nemowide2_layout;
+               device->packetsize = 512;
+               break;
        case PUCK2:
        case NEMOWIDE2:
        case SMART:

diff --git a/src/serial_posix.c b/src/serial_posix.c
index 8872982..7a3fd81 100644
--- a/src/serial_posix.c
+++ b/src/serial_posix.c
@@ -568,6 +568,10 @@ dc_serial_configure (dc_iostream_t *abstract, unsigned int baudrate, unsigned in
                return DC_STATUS_INVALIDARGS;
        }
 
+       // disable parity checking to fix the 0xEC CP210x driver bug
+       // confirmed: without parity check enabled, everything is working again on linux
+       tty.c_iflag &= ~(INPCK);
+
        // Apply the new settings.
        if (tcsetattr (device->fd, TCSANOW, &tty) != 0 && NOPTY) {
                int errcode = errno;
@@ -765,7 +769,7 @@ dc_serial_read (dc_iostream_t *abstract, void *data, size_t size, size_t *actual
                ssize_t n = read (device->fd, (char *) data + nbytes, size - nbytes);
                if (n < 0) {
                        int errcode = errno;
-                       if (errcode == EINTR || errcode == EAGAIN)
+                       if (errcode == EINTR || errcode == EAGAIN  || errcode == EWOULDBLOCK)
                                continue; // Retry.
                        SYSERROR (abstract->context, errcode);
                        status = syserror (errcode);
```

**Comment by jefdriesen** [comment]
Great, that confirms that the input parity checking (INPCK) is indeed the issue here. I'll need to investigate a bit whether removing it causes side effects or not. It's been a while since I wrote that code, so that will take some time, especially because I'm busy diving this week :-)

I can always use an extra memory dump for testing purposes, so if you don't mind sharing it, sure. You can attach it the bug report, or send it by email.

For the packet size, it's certainly possible things have changed. For the newer devices, I didn't always check in detail and we just picked the same as the previous model. For the earlier models I did some timing tests (and some advice from Mares) to pick the size. I'll put that on my todo list.

**Comment by h3llra1ser** [comment]
I've reported the driver thing upstream to Johan already, I dont think that there's anything wrong with your code.

To be able to read out the puck I'm using the dctool with disabled INPCK the last days. I suggest you **don't disable** parity checking since I've encountered several transmission errors with a "salty moist Puck" without rinsing it in fresh water first.
Disabled INPCK results in funny peaks in the depth and/or temperature graph, which remind me to clean the equipment... 

I'm still busy diving too atm ;)
Please leave this issue open - when returning home I'll dump the memory on a working system with parity check enabled. Dont want to provide possible garbage caused by parity errors.
I try to time the whole mem dump with 256 and 512 packet size also.

**Comment by h3llra1ser** [comment]
I've successfully dumped the whole memory of my Puck with the new kernel driver patch, feel free to use it as a sample: [PuckPro.bin.gz](https://github.com/libdivecomputer/libdivecomputer/files/7213680/PuckPro.bin.gz)

I've also did time two whole mem dumps with 256 and 512 packet size, for me it seems that the 512 bytes are faster because there are half the packet requests?!
But that could also be slower if only certain dive logs are requested...

```
time libdivecomputer/examples/dctool -d "Mares Puck Pro" dump -o PuckPro.bin /dev/ttyUSB0

# 256 bytes packets
	real	0m41,457s
	user	0m0,165s
	sys	0m1,491s

# 512 bytes packets
	real	0m35,928s
	user	0m0,203s
	sys	0m1,423s

```

**Comment by jefdriesen** [comment]
Good you already reported the issue upstream. I was planning to do the same, but didn't had time for it yet. Looks like this will be fixed in the kernel: https://lore.kernel.org/all/20210922113100.20888-1-johan@kernel.org/

For the choice of the packet size, the timing analysis I did years ago was for an Icon HD. As expected, very small packets are indeed noticeable slower due to the extra overhead. But once the size is large enough the difference is negligible. For the Icon HD the optimum was around 4096 bytes. If I remember correctly, that was also the block size of the underlying flash memory. See commit 9394773cd25b58ae066c0b367f67a01c632ef273 for details. For the other models this is probably going to be similar. I'll check whether there are also other models where Mares is using 512 byte packets, so we can update all of them at once.
