### ISSUE TITLE
Support for Seac Dive Computers

### ISSUE THREAD

**Issue by jwobser** [libdivecomputer/libdivecomputer#24]
I would like to try help add support for Seac computers.

PortMon will not work on 64bit windows, but I was able to capture log files using HHD software's serial monitor.

There are 2 html logs, one for RX and one for TX, in the attached zip file. Unfortunately the software I used will not allow them to be exported together.
The attached text file has timestamped data in both RX and TX, but not the full hex data for each transmission. 
[Seac - libdivecomputer.zip](https://github.com/libdivecomputer/libdivecomputer/files/8320396/Seac.-.libdivecomputer.zip)
[timestamped.txt](https://github.com/libdivecomputer/libdivecomputer/files/8320398/timestamped.txt)

The log file below is from the manufacturer's software (SeacSync). 
[log_2dives.log](https://github.com/libdivecomputer/libdivecomputer/files/8320464/log_2dives.log)

Finally I have the SQLite database for the two dives that were imported from this sync event.
[divesDB_2dives.zip](https://github.com/libdivecomputer/libdivecomputer/files/8320486/divesDB_2dives.zip)

The raw hex data is in the attached zip below, but again unfortunately it is separated into non-timestamped TX and RX files.
[hex_files.zip](https://github.com/libdivecomputer/libdivecomputer/files/8320531/hex_files.zip)

The USB to UART bridge is a silicon labs CP210x.
![image](https://user-images.githubusercontent.com/4492291/159396366-49c4cd13-2305-47a8-b72e-85c605a45555.png)

### Serial configuration
Baud Rate: 115,200
WordLength: 8
1 Stop Bit
No Parity

**Comment by jefdriesen** [comment]
The data looks good. The fact that the Tx and Rx are separated is a bit less practical to work with. The timestamped format is something I can easily parse out of the box (because it's very similar to the portmon output), so if you can somehow export the capture file to that format with the full data, that would be perfect.

Which Seac dive computer did you download from?

Anyway, the packet data structure looks very straightforward:
```
CMD := 61 55 len(2) data(len-4) crc(2)
RSP :=    55 len(2) data(len-4) crc(2)
```
And it looks like first some kind of index is being downloaded, and then the full dive data. So at first sight, this doesn't look very complicated.

**Comment by jwobser** [comment]
The computer is the [Seac Action](https://b2b.seacsub.com/single-product.php?pc=1600006&p=action-hr&cctc=2&cct=scuba-computer-e-consolle&shop=seacsub&language=en), though I believe that it would also work on the [Screen](https://b2b.seacsub.com/single-product.php?pc=1600008&p=screen&cctc=2&cct=scuba-computer-e-consolle&shop=seacsub&language=en).

I think this file should be a little bit more useful, although it's not in the same 1 row per packet format.
There is a header with the time stamp, then 16 hex bytes followed by the ascii representation.

I will keep trying to improve the export format so you won't have to clean it up as much.
[timestamped2.txt](https://github.com/libdivecomputer/libdivecomputer/files/8358468/timestamped2.txt)

**Comment by jefdriesen** [comment]
I've made some progress. I've prepared a first build that should be able to read out the dive headers. Can you give it a try and email me the results (seac.log)? You can download the binary here: https://libdivecomputer.org/builds/experimental/windows/seac.exe 
It's a command-line application which you need to execute with these options:
`seac.exe -vv -l seac.log -f screen download -o seac.xml COMx`
Replace `COMx` with the correct serial port.

**Comment by jwobser** [comment]
Looks like it worked! Log attached.

[seac.log](https://github.com/libdivecomputer/libdivecomputer/files/8426983/seac.log)

**Comment by jefdriesen** [comment]
Can you download the latest build (same link), and try these commands:
```
seac.exe -vv -l seac-8.log -f screen read -a 0x12300 -c 0x8 -o dummy COMx
seac.exe -vv -l seac-80.log -f screen read -a 0x12300 -c 0x80 -o dummy COMx
seac.exe -vv -l seac-800.log -f screen read -a 0x12300 -c 0x800 -o dummy COMx
```

**Comment by jwobser** [comment]
I haven't touched the computer since the last test, but now it is not working with the original .exe or the latest one you provided.
I double checked using the SeacSync tool and that was still downloading okay, so the serial adapter is still working.

[test2.zip](https://github.com/libdivecomputer/libdivecomputer/files/8456005/test2.zip)

I'm attaching the Seac log (log.log) as well as the serial recording and the log output from your test program.

**Comment by jefdriesen** [comment]
Did you try all 3 variants? I expect some will indeed fail. The original command should still work.

**Comment by jwobser** [comment]
Yes I tried all three variants of the command.

Additionally I had saved the previous version of the binary and tried using that and it also failed. 

Looking at the SeacSync software log, it seems to identify that the dives are the same based on the data they contain, but uses a different index number to refer to them.

<img width="1270" alt="Screen Shot 2022-04-09 at 5 57 21 PM" src="https://user-images.githubusercontent.com/4492291/162592819-3bce7ed3-7fd4-4af7-a6f6-84abb4788a9a.png">

**Comment by jefdriesen** [comment]
Always attach the log of each attempt. Even the failed ones. The final fail/success status is not the most important info. It's the detailed info in the log that matters.

**Comment by jwobser** [comment]
[seac-8.log](https://github.com/libdivecomputer/libdivecomputer/files/8459161/seac-8.log)
[seac-80.log](https://github.com/libdivecomputer/libdivecomputer/files/8459162/seac-80.log)
[seac-800.log](https://github.com/libdivecomputer/libdivecomputer/files/8459163/seac-800.log)

No problem, I'll attach the log for every attempt from now on. Here are the three commands.

**Comment by jefdriesen** [comment]
All 3 logs show the same problem: no response at all from the dive computer. The fact that the previous build, which worked fine a few days ago, also fails seems to indicate there is some general issue with the connection. Did you do something different this time? Maybe try SeacSync first to confirm the connection is good, and then immediately run the test application afterwards?

**Comment by jwobser** [comment]
So I tried re-running the test applications multiple times, and they would work sporadically.
Unfortunately I don't have the serial recordings broken down by attempt, I just left it running through the whole process, hoping I could catch what is causing the intermittent behavior.

In the recording, the actions are in this order:
1) SeacSync reading the headers (0 dives were downloaded)
2) The original test binary, executed multiple times until I saw data coming back.
3) New test binary with 0x8, multiple runs
4) New test binary 0x80, multiple runs
5) New test binary 0x800, multiple runs

[seac-8.log](https://github.com/libdivecomputer/libdivecomputer/files/8555473/seac-8.log)
[seac-80.log](https://github.com/libdivecomputer/libdivecomputer/files/8555474/seac-80.log)
[seac-800.log](https://github.com/libdivecomputer/libdivecomputer/files/8555475/seac-800.log)
[full_log.txt](https://github.com/libdivecomputer/libdivecomputer/files/8555476/full_log.txt)
[packet_view.txt](https://github.com/libdivecomputer/libdivecomputer/files/8555479/packet_view.txt)
[seac_old_test_binary.log](https://github.com/libdivecomputer/libdivecomputer/files/8555481/seac_old_test_binary.log)
[seac_sync.log](https://github.com/libdivecomputer/libdivecomputer/files/8555482/seac_sync.log)

**Comment by jefdriesen** [comment]
These results look good. Note that there is no need to capture the communication when running the test application. It already writes everything I need to the log file. Capturing the communication is only useful for the SeacSync application. 

I have uploaded a new build. Same URL again. Test with these parameters:

`seac.exe -vv -l seac-download.log -f screen download -o dive.%n.bin -f raw COMx`

We also need to find out how much memory the dive computer has. Since there aren't enough dives on your computer yet to have filled up all memory, that's going to be some trial and error. Let's try to read 1M and see how far we get:

`seac.exe -vv -l seac-read.log -f screen read -a 0 -c 0x100000 -o seac.bin COMx`

**Comment by jwobser** [comment]
Here are the two logs. I repeated the read command several times but it was not working.

Seac advertises 40 hours of logging for scuba. Based on dive 62 being 62 minutes long and the log 
47kB I would expect ~1.8MB of storage.

[seac-download.log](https://github.com/libdivecomputer/libdivecomputer/files/8628030/seac-download.log)
[seac-read.log](https://github.com/libdivecomputer/libdivecomputer/files/8628031/seac-read.log)

**Comment by jefdriesen** [comment]
Did the read command always fail with the same error? It appears to reply with some (unknown) status code 0x30. That could indicate we are not allowed to read at memory address zero. Since the dives start at address 0x10000, let's try from there:

`seac.exe -vv -l seac-read.log -f screen read -a 0x10000 -c 0x400000 -o seac.bin COMx`

I also increased the size to 4M because your 62 dives are already 1.4M in total.

**Comment by jwobser** [comment]
Yes, I saw the same unknown status code response in previous attempts. I also had to re-try the command a couple times because I got a no response received. 

Reading starting from 0x10'000 worked until a certain address. 
Log below.

[seac-read.log](https://github.com/libdivecomputer/libdivecomputer/files/8631422/seac-read.log)

It looks like the manufacturer memset the device to 0xff, perhaps during final testing. So the first two bytes are a command response, and the last 3 are a checksum, resulting in 2048 bytes of dive data read from every read?

**Comment by jefdriesen** [comment]
It failed when trying to read past 2M. That probably means the device has 2M memory. But with no access to the first 64K bytes. Those 0xFF bytes are the content of erased flash memory, so that's expected.

I uploaded a new build, which contains basic support for parsing the data:
`seac.exe -vv -l seac-download.log -f screen download -o seac.xml COMx`
Carefully check the xml file for mistakes, and report those. The xml file can be imported into subsurface, which will make it much easier to spot mistakes.

**Comment by jwobser** [comment]
Looks like something went wrong after reading all the dives in.

I did pull in the .xml into subsurface and I can tell right away the timezones are going to be an issue. I had to handle the same thing when writing the sqlite db parser. Seac stores everything in UTC, and also makes a note of the current timezone.

For example, dive 62 was pulled in  2021 AUG 15 16:32, when the local time was actually 12:32. My time zone for that dive was EDT (-4:00).

[See here to decode](https://github.com/subsurface/subsurface/blob/ef0a6b7beea5a648991802f4520171379edceaeb/core/import-seac.c#L81) the time zone number to the offset. I read that offset into an iso date/time string, then use a helper function that returns the local time (which subsurface uses to timestamp dives).

```
[318.860774] Dive: number=62, size=47872, fingerprint=10201B0F0815
[318.863599] Creating the parser.
[318.864737] Registering the data.
[318.865891] Parsing the dive data.
[318.867182] Parsing the datetime.
[318.868595] Parsing the divetime.
[318.870366] ERROR: Unexpected header checksum. [in src/seac_screen_parser.c:195 (seac_screen_parser_samples_foreach)]
[318.875051] ERROR: Error parsing the divetime. [in examples/output_xml.c:249 (dctool_xml_output_write)]
[318.880065] ERROR: Error parsing the dive data. [in examples/dctool_download.c:99 (dive_cb)]
```

[seac-download.log](https://github.com/libdivecomputer/libdivecomputer/files/8680856/seac-download.log)
[seac.xml.log](https://github.com/libdivecomputer/libdivecomputer/files/8680859/seac.xml.log)

**Comment by jefdriesen** [comment]
That checksum error is really strange, especially because I can't reproduce with your data. I have temporary changed it into a non-fatal error, such that at least the samples end up in the xml file. Otherwise there isn't much to check. I've also updated the date/time parsing to take into account the timezone offset. Can you give the new build a try?

If you still get the checksum error with the new build, can you try a two-step approach:
```
seac.exe -vv -l seac-download.log -f screen download -o dive.%n.bin -f raw COMx
seac.exe -vv -l seac-parse.log -f screen parse -o seac.xml dive.*.bin
```
And attach the logs, along with all the dive.*.bin files.

**Comment by jwobser** [comment]
I had success with the single step this time. Depths, timestamps, ndl, and temperatures all look correct.

I did notice a few things (and I understand it's a dev build, so some of these features haven't even started to be implemented).

Dive 23 has a gas switch event from air to 22% and back. I see in the XML file both gases are detected, and in the 18:26 sample there is a mix change, but for some reason that isn't displayed in Subsurface.

It also looks like the CNS is not being read correctly. In dive 23, sample 5:56 is 0%, and sample 6:01 is 100%. Then at 09:21 it goes to 6553800.

Also the gradient factor from the dive header was not imported, and the computer type is also missing.

[seac.xml.log](https://github.com/libdivecomputer/libdivecomputer/files/8689211/seac.xml.log)
 [seac-download.log](https://github.com/libdivecomputer/libdivecomputer/files/8689194/seac-download.log)

The first image below is the import from libdivecomputer, while the second is importing the SeacSync DB.
![image](https://user-images.githubusercontent.com/4492291/168297588-c8f714a3-cbc1-4cfa-90d7-775e9cea166a.png)
![image](https://user-images.githubusercontent.com/4492291/168297651-3c6cfe47-9876-4386-99d6-92d1bf4cb281.png)

**Comment by jefdriesen** [comment]
The missing gas switch is probably an issue in the xml import. When downloading directly into subsurface, it's there. The CNS issue is fixed, and the dive mode (OC/Gauge/Freedive) has been added too.

The sqlite database from the SeacSync application you provided earlier only contains 3 dives. Can you download all 62 dives into SeacSync and attach the resulting database? Otherwise I can't check the data from the other dives.

**Comment by jwobser** [comment]
Hi Jef,

Here is the full DB.

[divesDB.zip](https://github.com/libdivecomputer/libdivecomputer/files/8702010/divesDB.zip)

**Comment by jwobser** [comment]
Here you go!
Are you able to add an `-r ##` option for say doing 3 retries before timing out? I usually have to run the command 3 times or so to get it to work. The first two times it will time out, before working correctly on the third. 

[seac-download.log](https://github.com/libdivecomputer/libdivecomputer/files/8749861/seac-download.log)
[seac.xml.log](https://github.com/libdivecomputer/libdivecomputer/files/8749862/seac.xml.log)

**Comment by jefdriesen** [comment]
Can you attach the logs of the failed attempts, such that I can check the exact behavior when it fails. Do you get a timeout with no data received at all, some error response, or even something else?

**Comment by jwobser** [comment]
Here is the error message that I get:

```INFO: Write: size=8, data=6155000618331923
INFO: Read: size=0, data=
ERROR: Failed to receive the packet header. [in src/seac_screen.c:138 (seac_screen_receive)]
ERROR: Failed to receive the response. [in src/seac_screen.c:202 (seac_screen_packet)]
ERROR: Failed to send the info command. [in src/seac_screen.c:352 (seac_screen_device_foreach)]
ERROR: Error downloading the dives. [in examples/dctool_download.c:228 (download)]
ERROR: Timeout

Log file and serial recording are attached. I terminated it with ^C once data started coming back
[serial_log.txt](https://github.com/libdivecomputer/libdivecomputer/files/8754785/serial_log.txt)
[seac-download.log](https://github.com/libdivecomputer/libdivecomputer/files/8754786/seac-download.log)
.

**Comment by jefdriesen** [comment]
That's a timeout error with no data received. I have uploaded a new build with n automatic retry mechanism.

No need to attach the serial capture or XML file. Just the log file is all I need for now.

**Comment by jwobser** [comment]
That works pretty consistently. I was able to run it 5 times and it worked every time.
With the old version if I were to wait ~ >1 second between runs it would timeout every time.

[seac-download.log](https://github.com/libdivecomputer/libdivecomputer/files/8754953/seac-download.log)

**Comment by jefdriesen** [comment]
Do you also see such timeouts with the SeacSync application? It looks like you only get the timeout on the very first request, so it could be that we are trying to send too soon, when the dive computer isn't ready yet.

**Comment by jefdriesen** [comment]
I'm not sure what the purpose of the 0x61 byte is. It's send before every command, and even 3 times before a read command. But I suspect it's not really part of the command. For the read command, I only send it once, and that works just fine. It's also only the first command that fails. The IOCTL_SERIAL_SET_TIMEOUTS is for setting the read/write timeouts. The SeacSync applications sets it repeatedly, but that's simply not necessary.

Anyway, I have uploaded a new build with a larger delay (500 instead of 100 ms) before sending the first command. Let's see if that avoids the problem or not. Note that the retrying will still kick in if the delay doesn't work, so you need to inspect the log for the error message.

**Comment by jwobser** [comment]
Same result:

```
[0.006970] VERSION 0.8.0-devel (f182af6cd76a662ac0892db286a16b5a96ed0258)
[0.013379] Opening the I/O stream (serial, COM3).
[0.016923] INFO: Open: name=COM3
[0.136305] Opening the device (Seac Screen).
[0.140640] INFO: Configure: baudrate=115200, databits=8, parity=0, stopbits=0, flowcontrol=0
[0.161955] INFO: Timeout: value=1000
[0.164134] INFO: Sleep: value=500
[0.685584] INFO: Purge: direction=3
[0.689954] Registering the event handler.
[0.692601] Registering the cancellation handler.
[0.696350] Downloading the dives.
[0.698170] Event: progress 0.00% (0/2031616)
[0.702061] INFO: Write: size=8, data=6155000618331923
[1.705843] INFO: Read: size=0, data=
[1.709825] ERROR: Failed to receive the packet header. [in src/seac_screen.c:142 (seac_screen_receive)]
[1.718115] ERROR: Failed to receive the response. [in src/seac_screen.c:206 (seac_screen_packet)]
[1.725749] INFO: Sleep: value=100
[1.827840] INFO: Purge: direction=1
[1.835489] INFO: Write: size=8, data=6155000618331923
[1.864251] INFO: Read: size=3, data=550107
[1.866895] INFO: Read: size=261
```

**Comment by jefdriesen** [comment]
Let's try something else. I've uploaded a new version which sends the 0x61 prefix separately from the main command, and another one which doesn't send it at all:
https://libdivecomputer.org/builds/experimental/windows/seac.exe
https://libdivecomputer.org/builds/experimental/windows/seac-without-prefix.exe

**Comment by jwobser** [comment]
I completely turned off the DC, and unplugged the serial adapter between runs to ensure that the line was not just staying awake.

Looks like it works fine without 0x61, just needs to retry once after the initial send to wake it up.

I'm testing pulling down all 62 dives currently, but no hang-ups so far.

Separate:
```
[0.218233] Registering the event handler.
[0.219808] Registering the cancellation handler.
[0.221954] Downloading the dives.
[0.223737] Event: progress 0.00% (0/2031616)
[0.225916] INFO: Write: size=1, data=61
[0.228111] INFO: Write: size=7, data=55000618331923
[0.256796] INFO: Read: size=3, data=550107
[0.259033] INFO: Read: size=261, data=1833020000000100000041000
```

Without:
```
[0.225213] Registering the event handler.
[0.226921] Registering the cancellation handler.
[0.229252] Downloading the dives.
[0.230738] Event: progress 0.00% (0/2031616)
[0.232762] INFO: Write: size=7, data=55000618331923
[1.247210] INFO: Read: size=0, data=
[1.249304] ERROR: Failed to receive the packet header. [in src/seac_screen.c:151 (seac_screen_receive)]
[1.253340] ERROR: Failed to receive the response. [in src/seac_screen.c:215 (seac_screen_packet)]
[1.258189] INFO: Sleep: value=100
[1.373779] INFO: Purge: direction=1
[1.376365] INFO: Write: size=7, data=55000618331923
[1.405201] INFO: Read: size=3, data=550107
[1.407455] INFO: Read: size=261, data= ...
[1.431496] INFO: Write: size=7, data=550006183469C4
[1.460111] INFO: Read: size=3, data=550107
[1.461481] INFO: Read: size=261, data= ...
[1.486156] Event: model=1 (0x00000001), firmware=1000070 (0x000f4286), serial=2566 (0x00000a06)
[1.490529] Event: vendor= ...
[1.510444] Event: vendor= ...
[1.533763] INFO: Write: size=7, data=550006184057D7
[1.536552] INFO: Read: size=3, data=55000F
[1.538694] INFO: Read: size=13, data=1840000000010000003E09A6BF
[1.541432] Event: progress 0.00% (8/2039808)
[1.542837] INFO: Write: size=11, data=55000A18410000003EEBB5
[1.551126] INFO: Read: size=3, data=55000B
[1.552808] INFO: Read: size=9, data=18410015FB8009A6FC
[1.555515] INFO: Write: size=15, data=55000E18420015FB80000000809F25
[1.627561] INFO: Read: size=3, data=550807
[1.773029] INFO: Read: size=2053, data=...
```

Logs:
[seac-download.log](https://github.com/libdivecomputer/libdivecomputer/files/8773197/seac-download.log)
[seac-without.log](https://github.com/libdivecomputer/libdivecomputer/files/8773199/seac-without.log)

**Comment by jefdriesen** [comment]
The version which wrote the 0x61 byte separately did work, even without needing a retry. But the version which doesn't send it all also worked (although only after a retry). Maybe we just need to send it at startup to "wakeup" the dive computer? Can you try that:
https://libdivecomputer.org/builds/experimental/windows/seac.exe

**Comment by jwobser** [comment]
The xml file hash changed, and it looks like the fingerprint is getting an `0A` prepended to it versus the older revisions.
![image](https://user-images.githubusercontent.com/4492291/171060233-6a2463a1-8462-41c0-9382-cdee2f20a59e.png)


Reading did work without retry at least:  
_(I truncated the lines to 60 chars wide)_
```
[0.028198] INFO: Configure: baudrate=115200, databits=8, parity=0, stopbits=0, flowcontrol=0
[0.051591] INFO: Timeout: value=1000
[0.052996] INFO: Sleep: value=100
[0.164754] INFO: Purge: direction=3
[0.167700] INFO: Write: size=1, data=61
[0.169600] INFO: Write: size=7, data=55000618331923
[0.198336] INFO: Read: size=3, data=550107
[0.199704] INFO: Read: size=261, data=1833020000000100000041000000
[0.224812] INFO: Write: size=7, data=550006183469C4
[0.253497] INFO: Read: size=3, data=550107
[0.255302] INFO: Read: size=261, data=18342604151E0500E60701000000
```
[seac-download.log](https://github.com/libdivecomputer/libdivecomputer/files/8800744/seac-download.log)

**Comment by jefdriesen** [comment]
Sending the byte once appears to work. That means we're almost done.

I've prepared a build that you can use with subsurface. Download the dll, remove the ".seac" suffix, and copy it into the subsurface installation directory. (Backup the existing dll to be able to restore it.) Start subsurface and try to download your dives. Carefully check all dives again for errors.
https://libdivecomputer.org/builds/experimental/windows/libdivecomputer-0.seac.dll

**Comment by jwobser** [comment]
Yep the 64bit version worked.

I just diff'd the ssrf file for the database import and also the libdivecomputer import.
All the samples are perfect.

The only differences are in descriptions of the events and cylinders, and they are not important.

The one last thing is the gradient factors. I don't know if Seac stores that value raw in computer, or if it references the user "conservatism level" setting (0-5). Either way it's extra data that probably isn't relevant to recreational divers.

![image](https://user-images.githubusercontent.com/4492291/171408587-371b2817-715e-4796-8df6-58957311a91c.png)

**Comment by jefdriesen** [comment]
I have pushed the changes to master.

Reporting GF isn't supported in libdivecomputer yet, but it's on the todo list.
