### ISSUE TITLE
CRC mismatch on Suunto EON Steel

### ISSUE THREAD

**Issue by latishab** [libdivecomputer/libdivecomputer#36]
I'm working on integrating libdivecomputer support with Swift for iOS development. While attempting to connect to and communicate with a Suunto D5 dive computer, I'm encountering several issues:

- BLE Connection: The initial Bluetooth Low Energy (BLE) connection appears to be successful.
- Service and Characteristic Discovery: The correct service (98AE7120-E62E-11E3-BADD-0002A5D5C51B) and characteristics (C6339440-E62E-11E3-A5B3-0002A5D5C51B for write, D0FD6B80-E62E-11E3-A2E9-0002A5D5C51B for notify) are discovered.
- Notification Enabling: Notifications are successfully enabled.
- Command Sending: The suunto_eonsteel_send function appears to execute without errors, sending a command (0000) with 4 bytes of data.
- Data Reception: The suunto_eonsteel_receive_ble function receives data, but encounters the following issues:
    1. Only 5 bytes are received, which seems insufficient.
    2. There's a CRC mismatch: Received CRC is 75b175c2, but calculated CRC is d202ef8d.
- Disconnection: The device disconnects after these errors occur.

Current Environment:
Language: Swift, C
Device: Suunto D5

Questions and Areas for Investigation:
- Why is there a discrepancy between the amount of data sent (20 bytes) and received (5 bytes)?
- What could be causing the CRC mismatch?

Any insights or suggestions for troubleshooting these issues would be greatly appreciated. I can provide additional code snippets or logs if needed.

Here is my code snippet of what I am trying to do:
`
dc_status_t open_suunto_eonsteel(device_data_t *data, const char *devaddr) {
    dc_status_t rc = DC_STATUS_SUCCESS;
    data->device = NULL;
    data->context = NULL;
    data->iostream = NULL;
    unsigned int model = 2;  // Suunto D5 model number
    
    rc = dc_context_new(&data->context);
    if (rc != DC_STATUS_SUCCESS) {
        printf("Failed to create libdc context\n");
        return rc;
    }
    
    // Open BLE connection
    rc = ble_packet_open(&data->iostream, data->context, devaddr, data);
    if (rc != DC_STATUS_SUCCESS) {
        printf("Failed to open BLE connection\n");
        dc_context_free(data->context);
        return rc;
    }
    
    rc = suunto_eonsteel_device_open(&data->device, data->context, data->iostream, model);
    if (rc != DC_STATUS_SUCCESS) {
        printf("Failed to open Suunto EON Steel device\n");
        dc_iostream_close(data->iostream);
        dc_context_free(data->context);
        return rc;
    }
    
    return rc;
}
`

Here is also my repo of where I put the code: https://github.com/latishab/libdc-swift

I also noticed that when I imported the include and src folder, i got this warning "Implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'unsigned int'" in most of the dive computer header and c files.

I wonder if this is the culprit, does it affects the CRC?? if yes, what should i do? i mean the code was like that from the first place.

**Comment by jefdriesen** [comment]
Do you have some logs containing the transferred data? Your logic looks correct to me, but without any data I have no clue about what goes wrong. A 5 byte response is likely too short.

**Comment by latishab** [comment]
Issue closed. 

I figured out there is something wrong with the IO. I ended up doing partial reads up to the requested size. And turns out something was wrong with my ble object setup.
