### ISSUE TITLE
Dive Rite Nitek Q Failed to receive the answer

### ISSUE THREAD

**Issue by joe8mofo** [libdivecomputer/libdivecomputer#6]
I am unable to pull dives from my Nitek Q on Windows or Linux. It always errors out and seems to be failing to handshake. Attached is the log; no dumpfile was created.
[subsurface.log](https://github.com/libdivecomputer/libdivecomputer/files/3369859/subsurface.log)

**Comment by jefdriesen** [comment]
Did it ever work before? Or is this the first time you are trying to download dives?

A common reason for this kind of error is a low battery. Often the PC interface requires more power than during diving. Thus it's not uncommon to have enough battery left for diving, but not anymore for downloading dives.

**Comment by joe8mofo** [comment]
It did work before; the battery is full. Is there any further way of diagnosing this?

**Comment by jefdriesen** [comment]
Has anything changed since last time it worked (differerent usb port, different cable, etc)? Are you able to download with the Diverite software?

**Comment by jefdriesen** [comment]
Without further information I can't diagnose the problem.
