### ISSUE TITLE
Mares Puck Pro

### ISSUE THREAD

**Issue by Patriboom** [libdivecomputer/libdivecomputer#7]
Hello, 
thanks for all you have done already. 
I use libdivecomputer since almost 10 years now.  I was doing so with Suundo Gekko.  This computer just died few months ago.  I bought a Mares Puck Pro
With same same working command ( under Linux console ), I get an error with the Mares.

My command is: 
`/usr/bin/universal -d /home/mySub/SubSubDir/Log_LogName.xml  -b puck /dev/ttyUSB0 `

I get such result, every time: 

`DATETIME 2019-07-22T00:05:37Z (1563753937)
VERSION 0.4.2
Opening the device (Mares Puck, /dev/ttyUSB0).
ERROR: Failed to receive the answer. [in mares_common.c:113 (mares_common_packet)]
ERROR: Failed to receive the answer. [in mares_common.c:113 (mares_common_packet)]
ERROR: Failed to receive the answer. [in mares_common.c:113 (mares_common_packet)]
ERROR: Failed to receive the answer. [in mares_common.c:113 (mares_common_packet)]
ERROR: Failed to receive the answer. [in mares_common.c:113 (mares_common_packet)]
universal.c:669: Error opening device.
Result: Timeout
`

Over that, the dive computer bips, and then starts a count down from 9 to 1, all screen working on such countdown.

Before to submit the command, I set divecomputer under « PC connect  » mode.  The cable LED from green turns to red.

What have I to do  ? 

Thanks.

**Comment by Patriboom** [comment]
Trying with device name
`/usr/bin/universal -d /home/patrick/MesSites/Plongee/temp/Registre/Log_1563674316.xml  -n "Mares Puck Pro" /dev/ttyUSB0`

Get the following result:

`Opening the device (Mares Puck Pro, /dev/ttyUSB0).
ERROR: Device or resource busy (16) [in serial_posix.c:107 (serial_open)]
ERROR: Failed to open the serial port. [in mares_iconhd.c:288 (mares_iconhd_device_open)]
universal.c:669: Error opening device.
Result: Input/output error
`

**Comment by Patriboom** [comment]
Dive computer transferred its data when I tried it with Mares software under windows 7.
Now, I want it under Linux, using libdivecomputer.
Thanks again.

**Comment by morejanus** [comment]
> On Jul 21, 2019, at 5:11 PM, Patrick Allaire <notifications@github.com> wrote:
> 
> Hello,
> thanks for all you have done already.
> I use libdivecomputer since almost 10 years now. I was doing so with Suundo Gekko. This computer just died few months ago. I bought a Mares Puck Pro
> With same same working command ( under Linux console ), I get an error with the Mares.
> 
> My command is:
> /usr/bin/universal -d /home/mySub/SubSubDir/Log_LogName.xml -b puck /dev/ttyUSB0

I’m making a guess here, but try using ‘iconhd’ instead of ‘puck’ as the backend. The Puck Pro is not actually in the ‘puck’ family.

Janice

**Comment by Patriboom** [comment]
Seams to work!
Thanks.

This is the working command for me:
`/usr/bin/universal -d /home/patrick/MesSites/Plongee/temp/Registre/Log_1563674316.xml  -b iconhd /dev/ttyUSB1 -n "Mares Puck Pro"`

I defined both -b (backend) and -n (name) option
