### ISSUE TITLE
-b and -n associations

### ISSUE THREAD

**Issue by Patriboom** [libdivecomputer/libdivecomputer#8]
Hello all, 

I'm working on http://plongee.ca   a website specialized for diving and want to make it easy for user.  So, I would like to double check the proper association for every computer recognized by libdivecomputer.
For now, I start with 

Maker | -b | -n
-- | -- | --
Suunto | solution | Suunto Solution
Suunto | eon | Suunto Eon
Suunto | eon | Suunto Solution Alpha
Suunto | eon | Suunto Solution Nitrox
Suunto | eon | Suunto Spyder
Suunto | eon | Suunto Stinger
Suunto | eon | Suunto Mosquito
Suunto | eon | Suunto D3
Suunto | vyper | Suunto Vyper
Suunto | vyper | Suunto Vytec
Suunto | vyper | Suunto Cobra
Suunto | vyper | Suunto Gekko
Suunto | vyper | Suunto Zoop
Suunto | vyper2 | Suunto Vyper 2
Suunto | vyper2 | Suunto Cobra 2
Suunto | vyper2 | Suunto Vyper Air
Suunto | vyper2 | Suunto Cobra 3
Suunto | vyper2 | Suunto HelO2
Suunto | d9 | Suunto D9
Suunto | d9 | Suunto D6
Suunto | d9 | Suunto D4
Suunto | d9 | Suunto D4i
Suunto | d9 | Suunto D6i
Suunto | d9 | Suunto D9tx
Suunto | d9 | Suunto DX
Uwatec | aladin | Uwatec Aladin Air Twin
Uwatec | aladin | Uwatec Aladin Sport Plus
Uwatec | aladin | Uwatec Aladin Pro
Uwatec | aladin | Uwatec Aladin Air Z
Uwatec | aladin | Uwatec Aladin Air Z O2
Uwatec | aladin | Uwatec Aladin Air Z Nitrox
Uwatec | aladin | Uwatec Aladin Pro Ultra
Uwatec | memomouse | Uwatec Memomouse
Uwatec | smart | Uwatec Smart Pro
Uwatec | smart | Uwatec Galileo Sol
Uwatec | smart | Uwatec Galileo Luna
Uwatec | smart | Uwatec Galileo Terra
Uwatec | smart | Uwatec Aladin Tec
Uwatec | smart | Uwatec Aladin Prime
Uwatec | smart | Uwatec Aladin Tec 2G
Uwatec | smart | Uwatec Aladin 2G
Subgear | smart | Subgear XP-10
Uwatec | smart | Uwatec Smart Com
Uwatec | smart | Uwatec Aladin 2G
Uwatec | smart | Uwatec Smart Tec
Uwatec | smart | Uwatec Galileo Trimix
Uwatec | smart | Uwatec Smart Z
Subgear | smart | Subgear XP Air
Reefnet | sensus | Reefnet Sensus
Reefnet | sensuspro | Reefnet Sensus Pro
Reefnet | sensusultra | Reefnet Sensus Ultra
Oceanic | sensusultra | Oceanic Versa Pro
Aeris | atom2 | Aeris Atmos 2
Oceanic | atom2 | Oceanic Pro Plus 2
Aeris | atom2 | Aeris Atmos AI
Oceanic | vtpro | Oceanic VT Pro
Sherwood | vtpro | Sherwood Wisdom
Aeris | vtpro | Aeris Elite
Genesis | vtpro | Genesis React Pro
Oceanic | vtpro | Oceanic Veo 200
Oceanic | veo250 | Oceanic Veo 250
Seemann | veo250 | Seemann XP5
Oceanic | veo250 | Oceanic Veo 180
Aeris | veo250 | Aeris XR-2
Sherwood | veo250 | Sherwood Insight
Oceanic | veo250 | Oceanic Atom 1.0
Aeris | veo250 | Aeris Epic
Oceanic | veo250 | Oceanic VT3
Aeris | veo250 | Aeris Elite T3
Oceanic | veo250 | Oceanic Atom 2.0
Oceanic | veo250 | Oceanic Geo
Aeris | veo250 | Aeris Manta
Oceanic | veo250 | Oceanic Datamask
Aeris | veo250 | Aeris Compumask
Aeris | veo250 | Aeris F10
Oceanic | veo250 | Oceanic OC1
Sherwood | veo250 | Sherwood Wisdom 2
Sherwood | veo250 | Sherwood Insight 2
Genesis | veo250 | Genesis React Pro White
Tusa | veo250 | Tusa Element II (IQ-750)
Oceanic | veo250 | Oceanic Veo 1.0
Oceanic | veo250 | Oceanic Veo 2.0
Oceanic | veo250 | Oceanic Veo 3.0
Tusa | veo250 | Tusa Zen (IQ-900)
Tusa | veo250 | Tusa Zen Air (IQ-950)
Aeris | veo250 | Aeris Atmos AI 2
Oceanic | veo250 | Oceanic Pro Plus 2.1
Oceanic | veo250 | Oceanic Geo 2.0
Oceanic | veo250 | Oceanic VT4
Oceanic | veo250 | Oceanic OC1
Oceanic | veo250 | Oceanic Atom 3.0
Hollis | veo250 | Hollis DG03
Oceanic | veo250 | Oceanic OCS
Oceanic | veo250 | Oceanic OC1
Oceanic | veo250 | Oceanic VT 4.1
Aeris | veo250 | Aeris Epic
Aeris | veo250 | Aeris Elite T3
Oceanic | veo250 | Oceanic Atom 3.1
Aeris | veo250 | Aeris A300 AI
Sherwood | veo250 | Sherwood Wisdom 3
Sherwood | veo250 | Sherwood Amphos
Oceanic | veo250 | Oceanic Pro Plus 3
Oceanic | veo250 | Oceanic OCi
Mares | nemo | Mares Nemo
Mares | nemo | Mares Nemo Steel
Mares | nemo | Mares Nemo Titanium
Mares | nemo | Mares Nemo Excel
Mares | nemo | Mares Nemo Apneist
Mares | puck | Mares Puck
Mares | puck | Mares Puck Air
Mares | puck | Mares Nemo Air
Mares | puck | Mares Nemo Wide
Mares | darwin | Mares Darwin
Mares | darwin | Mares M1
Mares | darwin | Mares M2
Mares | darwin | Mares Darwin Air
Mares | darwin | Mares Matrix
Mares | iconhd | Mares Icon HD
Mares | iconhd | Mares Icon HD Net Ready
Mares | iconhd | Mares Puck Pro
Mares | iconhd | Mares Nemo Wide 2
Mares | iconhd | Mares Puck 2
Heinrichs | ostc | Heinrichs Weikamp OSTC
Heinrichs | ostc | Heinrichs Weikamp OSTC Mk2
Heinrichs | ostc | Heinrichs Weikamp OSTC 2N
Heinrichs | frog | Heinrichs Weikamp Frog
Heinrichs | ostc3 | Heinrichs Weikamp OSTC 3
Cressi | edy | Cressi Edy
Cressi | leonardo | Cressi Leonardo
Zeagle | n2ition3 | Zeagle N2iTiON3
Apeks | cobalt | Apeks Quantum X
DiveRite | cobalt | DiveRite NiTek Trio
Scubapro | cobalt | Scubapro XTender 5
Sherwater | predator | Shearwater Predator
Sherwater | petrel | Shearwater Petrel

Is that ok ? 

Thanks.

**Comment by jefdriesen** [comment]
There are several errors in your table and the list is also outdated. It looks like you are using an outdated version. Newer version support querying the supported dive computers.

**Comment by Patriboom** [comment]
Ah!  Ok.
It was from the version distributed by Debian.
I'll take the actual git version.

**Comment by Patriboom** [comment]
I see ... many more models available.
