### ISSUE TITLE
*** stack smashing detected ***

### ISSUE THREAD

**Issue by Patriboom** [libdivecomputer/libdivecomputer#9]
Hello everyone, 

thanks for your work, Jef.

I downloaded from Mares Puck Pro  yesterday with the following command
`/usr/bin/universal -d /home/user/SubDir/temp/Log_Mares1563674316.xml  -n "Mares Puck Pro" /dev/ttyUSB0`
under Linux Debian 10

Today, the same command gives me such result:
`DATETIME 2019-07-23T18:58:55Z (1563908335)
VERSION 0.7.0-devel (d5aa15c1c5deb4056d9bc05f8bc3bc06f7d1229f)
*** stack smashing detected ***: <unknown> terminated
Abandon
`
Same result with
`/usr/bin/universal -d /home/user/SubDir/temp/Log_Mares1563674316.xml  -b iconhd /dev/ttyUSB0`

**Comment by Patriboom** [comment]
It must not be from 
```
typedef struct mares_iconhd_model_t {
	unsigned char name[16 + 1];
	unsigned int id;
} mares_iconhd_model_t;

```
because "Mares Puck Pro" is 14 long ( less than 16 + 1)

I may come from
typedef struct mares_iconhd_device_t {
	dc_device_t base;
	dc_iostream_t *iostream;
	const mares_iconhd_layout_t *layout;
	unsigned char fingerprint[10];    ---- How long is my fingerprint ?   Don't know.  Doesn't matter either when we don't define fingerprint like the command given up
	unsigned int fingerprint_size;
	unsigned char version[140];  ----  Can be surprising!
	unsigned int model;
	unsigned int packetsize;
	unsigned char cache[20]; ----   Depend on what the cache does, 20 is pretty small
	unsigned int available;
	unsigned int offset;
} mares_iconhd_device_t;

Bellow: undefined char lenght:
static dc_status_t mares_iconhd_device_set_fingerprint (dc_device_t *abstract, const unsigned char data[], unsigned int size);
static dc_status_t mares_iconhd_device_read (dc_device_t *abstract, unsigned int address, unsigned char data[], unsigned int size);

[...]

mares_iconhd_read (mares_iconhd_device_t *device, unsigned char data[], size_t size)

All this from the mares_iconhd.c file.

**Comment by jefdriesen** [comment]
I suspect you are trying to run the old `universal` tool against a recent version of the libdivecomputer library. That's simply not going to work. The `universal` tool has been removed and replaced with the more powerful `dctool` command-line application about three years ago. The public api has changed significantly since then, and I guess that is what causes the crash. Try using the `dctool` command-line application instead.

`
dctool -d "Mares Puck Pro" download -o output.xml /dev/ttyUSB0
`

**Comment by Patriboom** [comment]
Thanks again Jef!
`dctool -d "Mares Puck Pro" download -o output.xml /dev/ttyUSB0`  works good

I downloaded the entire git pack, then following the README
- make
- sudo make install


I'll try remove the entire libdivecomputer package with aptitude and redo the process.
I'll let you know the result


I wander if I should use dctool rather than universal for my application ?!?

What are the main differences between both ?

**Comment by Patriboom** [comment]
Universal doesn't work anymore since I uninstallled from my computer with aptitude even if I did
- make
- make install

But, still dctool works good.

I may look like crazy or dumb, but I also want the provide the most simples informations to my http://plongee.ca users.

Thanks for your support.

**Comment by jefdriesen** [comment]
> I wander if I should use dctool rather than universal for my application ?!?
> What are the main differences between both ?

Just use `dctool` and forget about `universal`! The latter is obsolete and is no longer available. The new `dctool` application can do everything `universal` ever did, and much more. You can see the available commands by running `dctool help`.

**Comment by Patriboom** [comment]
Nice, nice, nice.
Thanks.

**Comment by Patriboom** [comment]
Other question : 
with universal, we had the -f option ( fingerprint ) which permitted to start download from a specific dive log to the end.  Does any fingerprint option like this exist in dctool ?

**Comment by jefdriesen** [comment]
Yes, there is the -p (fingerprint) and -c (cachedir) option. Run `dctool help download` for a summary.

**Comment by Patriboom** [comment]
All my dumb questions will create a user manual !
Thanks again
